# Generated by Django 5.1.6 on 2025-02-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='came_out_on',
            field=models.DateField(),
        ),
    ]
