# Generated by Django 5.1.6 on 2025-02-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_game_came_out_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='made_by',
            new_name='author',
        ),
    ]
