# Generated by Django 5.1.4 on 2025-04-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_game_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='art',
            field=models.ImageField(default=None, null=True, upload_to='art'),
        ),
    ]
