# Generated by Django 5.1.4 on 2025-04-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_game_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='art',
            field=models.ImageField(blank=True, null=True, upload_to='art'),
        ),
    ]
